import SwiftUI

enum CatppuccinPalette {
    enum Latte {
        static let base      = Color(hex: "#eff1f5")
        static let mantle    = Color(hex: "#e6e9ef")
        static let crust     = Color(hex: "#dce0e8")
        static let surface0  = Color(hex: "#ccd0da")
        static let surface1  = Color(hex: "#bcc0cc")
        static let surface2  = Color(hex: "#acb0be")
        static let overlay0  = Color(hex: "#9ca0b0")
        static let overlay1  = Color(hex: "#8c8fa1")
        static let overlay2  = Color(hex: "#7c7f93")
        static let subtext0  = Color(hex: "#6c6f85")
        static let subtext1  = Color(hex: "#5c5f77")
        static let text      = Color(hex: "#4c4f69")
        static let lavender  = Color(hex: "#7287fd")
        static let blue      = Color(hex: "#1e66f5")
        static let sapphire  = Color(hex: "#209fb5")
        static let sky       = Color(hex: "#04a5e5")
        static let teal      = Color(hex: "#179299")
        static let green     = Color(hex: "#40a02b")
        static let yellow    = Color(hex: "#df8e1d")
        static let peach     = Color(hex: "#fe640b")
        static let maroon    = Color(hex: "#e64553")
        static let red       = Color(hex: "#d20f39")
        static let mauve     = Color(hex: "#8839ef")
        static let pink      = Color(hex: "#ea76cb")
        static let flamingo  = Color(hex: "#dd7878")
        static let rosewater = Color(hex: "#dc8a78")
    }

    enum Macchiato {
        static let base      = Color(hex: "#24273a")
        static let mantle    = Color(hex: "#1e2030")
        static let crust     = Color(hex: "#181926")
        static let surface0  = Color(hex: "#363a4f")
        static let surface1  = Color(hex: "#494d64")
        static let surface2  = Color(hex: "#5b6078")
        static let overlay0  = Color(hex: "#6e738d")
        static let overlay1  = Color(hex: "#8087a2")
        static let overlay2  = Color(hex: "#939ab7")
        static let subtext0  = Color(hex: "#a5adcb")
        static let subtext1  = Color(hex: "#b8c0e0")
        static let text      = Color(hex: "#cad3f5")
        static let lavender  = Color(hex: "#b7bdf8")
        static let blue      = Color(hex: "#8aadf4")
        static let sapphire  = Color(hex: "#7dc4e4")
        static let sky       = Color(hex: "#91d7e3")
        static let teal      = Color(hex: "#8bd5ca")
        static let green     = Color(hex: "#a6da95")
        static let yellow    = Color(hex: "#eed49f")
        static let peach     = Color(hex: "#f5a97f")
        static let maroon    = Color(hex: "#ee99a0")
        static let red       = Color(hex: "#ed8796")
        static let mauve     = Color(hex: "#c6a0f6")
        static let pink      = Color(hex: "#f5bde6")
        static let flamingo  = Color(hex: "#f0c6c6")
        static let rosewater = Color(hex: "#f4dbd6")
    }
}
